// Code generated by MockGen. DO NOT EDIT.
// Source: store.go

// Package mock is a generated GoMock package.
package mock

import (
	url "net/url"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// Store is a mock of Store interface.
type Store struct {
	ctrl     *gomock.Controller
	recorder *StoreMockRecorder
}

// StoreMockRecorder is the mock recorder for Store.
type StoreMockRecorder struct {
	mock *Store
}

// NewStore creates a new mock instance.
func NewStore(ctrl *gomock.Controller) *Store {
	mock := &Store{ctrl: ctrl}
	mock.recorder = &StoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Store) EXPECT() *StoreMockRecorder {
	return m.recorder
}

// Clear mocks base method.
func (m *Store) Clear() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clear")
	ret0, _ := ret[0].(error)
	return ret0
}

// Clear indicates an expected call of Clear.
func (mr *StoreMockRecorder) Clear() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*Store)(nil).Clear))
}

// Get mocks base method.
func (m *Store) Get(obscured *url.URL) (*url.URL, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", obscured)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *StoreMockRecorder) Get(obscured interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*Store)(nil).Get), obscured)
}

// Load mocks base method.
func (m *Store) Load(arg0 map[*url.URL]*url.URL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Load indicates an expected call of Load.
func (mr *StoreMockRecorder) Load(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*Store)(nil).Load), arg0)
}

// Put mocks base method.
func (m *Store) Put(obscured, original *url.URL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", obscured, original)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *StoreMockRecorder) Put(obscured, original interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*Store)(nil).Put), obscured, original)
}

// Remove mocks base method.
func (m *Store) Remove(obscured *url.URL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", obscured)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *StoreMockRecorder) Remove(obscured interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*Store)(nil).Remove), obscured)
}

// Size mocks base method.
func (m *Store) Size() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Size")
	ret0, _ := ret[0].(int)
	return ret0
}

// Size indicates an expected call of Size.
func (mr *StoreMockRecorder) Size() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Size", reflect.TypeOf((*Store)(nil).Size))
}
